# Generated by Django 5.0.7 on 2024-08-06 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='post',
            new_name='related_post',
        ),
    ]
